### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by TsvetanUsunov** [hyperobject/snap-nxt#1]
Hi
Is there documentation how to add and interface custom blocks on SNAP?
We have Embedded Linux board which runs SNAP https://www.olimex.com/Products/OLinuXino/A13/A13-OLinuXino-WIFI/ and I would like to add GPIO, SPI, UART, I2C controls as SNAP building blocks.
I probably will do it looking at your code, but if somewhere there is documentation and description how to create and interface custom blocks would help me a lot
Thanks!

**Comment by hyperobject** [comment]
Hi TsvetsanUsunov,
There is no full documentation now, but I can probably write some in the next week. 

Essentially, all you need to do is 'hook up' a Python hardware control module to the Snap! base server (http://www.github.com/technoboy10/snap-server). 

Hope that helps,
Technoboy10

**Comment by TsvetanUsunov** [comment]
Thanks! This is what I needed :) 
Now I'm asking myself how I missed it before.

**Comment by hyperobject** [comment]
I've created the first documentation page on the Snap! base server repo wiki. It describes how to create a block module from start to finish. Enjoy!

If you have any other questions, please file them as issues on the snap-server repo.

Happy Snap!ping!
